import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowRight, Sparkles } from "lucide-react";
import { PRESET_KEY } from "@/lib/presets";
import { TANK_IDEAS } from "@/lib/tank-ideas";
import { absoluteUrl } from "@/lib/site";

export const Route = createFileRoute("/tank-ideas/")({ head: () => ({ meta: [{ title: "Tank ideas and aquarium templates | FishTankr" }, { name: "description", content: "Browse freshwater aquarium ideas, then send a template straight into the FishTankr stocking calculator." }], links: [{ rel: "canonical", href: absoluteUrl("/tank-ideas") }] }), component: TankIdeas });
function TankIdeas() { const [level, setLevel] = useState("All"); const navigate = useNavigate(); const ideas = level === "All" ? TANK_IDEAS : TANK_IDEAS.filter((idea) => idea.level === level); const load = (id: string) => { sessionStorage.setItem(PRESET_KEY, id); navigate({ to: "/calculator" }); }; return <main className="mx-auto w-full max-w-7xl px-4 py-10 sm:px-6"><header className="max-w-3xl"><p className="science-label text-primary">Tank ideas</p><h1 className="mt-3 font-display text-4xl font-bold text-foreground sm:text-6xl">Start with a tank that already makes sense.</h1><p className="mt-5 text-base leading-relaxed text-muted-foreground">Browse practical freshwater starting points. Each template opens in the calculator so you can make it your own before you buy a thing.</p></header><div className="mt-8 flex gap-2"><button onClick={() => setLevel("All")} className={`rounded-full px-4 py-2 text-sm font-semibold ${level === "All" ? "bg-primary text-primary-foreground" : "bg-muted text-foreground"}`}>All ideas</button><button onClick={() => setLevel("Beginner")} className={`rounded-full px-4 py-2 text-sm font-semibold ${level === "Beginner" ? "bg-primary text-primary-foreground" : "bg-muted text-foreground"}`}>Beginner</button><button onClick={() => setLevel("Intermediate")} className={`rounded-full px-4 py-2 text-sm font-semibold ${level === "Intermediate" ? "bg-primary text-primary-foreground" : "bg-muted text-foreground"}`}>Intermediate</button></div><section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{ideas.map((idea) => <article key={idea.id} className="flex min-h-[280px] flex-col rounded-xl border bg-card p-5 shadow-sm"><div className="flex items-center justify-between text-xs font-semibold text-primary"><span>{idea.sizeLabel}</span><span>{idea.level}</span></div><h2 className="mt-5 font-display text-2xl font-bold text-foreground">{idea.name}</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{idea.summary}</p><div className="mt-5 flex flex-wrap gap-2">{idea.highlights.map((item) => <span key={item} className="rounded-full bg-muted px-2.5 py-1 text-xs text-muted-foreground">{item}</span>)}</div><div className="mt-auto flex gap-3 pt-6"><Link to="/tank-ideas/$slug" params={{ slug: idea.slug }} className="text-sm font-semibold text-foreground hover:text-primary">View idea</Link><button onClick={() => load(idea.id)} className="ml-auto inline-flex items-center gap-1 text-sm font-semibold text-primary">Try it <ArrowRight className="size-4" /></button></div></article>)}</section><div className="mt-12 flex items-center gap-3 border-t pt-8 text-sm text-muted-foreground"><Sparkles className="size-5 text-primary" />Templates are a starting point, not a stocking guarantee. Check the score after you tailor yours.</div></main>; }
