import { createFileRoute, Link } from "@tanstack/react-router";
import { PolicyPage, PolicySection } from "@/components/PolicyPage";
import { absoluteUrl } from "@/lib/site";

const path = "/terms";
export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of use | FishTankr" },
      {
        name: "description",
        content:
          "Terms for using FishTankr's aquarium planning and directory tools.",
      },
      { property: "og:url", content: absoluteUrl(path) },
    ],
    links: [{ rel: "canonical", href: absoluteUrl(path) }],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <PolicyPage
      eyebrow="Terms"
      title="Terms of use"
      intro="FishTankr is decision support for aquarium planning, not a substitute for direct observation or qualified advice. Last updated 27 August 2026."
    >
      <PolicySection title="Use of the tool">
        <p>
          You may use FishTankr for personal aquarium planning and share links
          generated by the service. Do not misuse the service, attempt to access
          other users’ private data, upload unlawful content, or rely on a
          shared tank link as proof that a setup is safe.
        </p>
      </PolicySection>
      <PolicySection title="No guarantee">
        <p>
          Scores are estimates based on incomplete species and setup data.
          Aquarium outcomes depend on water chemistry, individual animals,
          husbandry, equipment, disease and other conditions the app cannot
          observe. Confirm decisions with current reputable sources and, for
          serious welfare concerns, an aquatic veterinarian or experienced
          professional.
        </p>
      </PolicySection>
      <PolicySection title="Availability and saved tanks">
        <p>
          The service is work in progress and may change or be unavailable.
          Anonymous saved tanks can become unrecoverable if browser data,
          session identifiers or the service database changes. Keep an
          independent copy of any plan that matters to you.
        </p>
      </PolicySection>
      <PolicySection title="Commercial links and intellectual property">
        <p>
          Some directory or product links may generate referral revenue or be
          paid placements; those relationships are disclosed. FishTankr content
          and code remain subject to their applicable rights, while third-party
          model and media credits are listed on the{" "}
          <Link
            to="/attribution"
            className="font-semibold text-primary underline"
          >
            attribution page
          </Link>
          .
        </p>
      </PolicySection>
    </PolicyPage>
  );
}
