-- Commercial transparency, privacy-safe product signals and evidence fields.
-- None of these fields affect welfare scoring.

ALTER TABLE public.aquarium_shops
  ADD COLUMN IF NOT EXISTS country_code text NOT NULL DEFAULT 'AU',
  ADD COLUMN IF NOT EXISTS featured boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS affiliate_url text,
  ADD COLUMN IF NOT EXISTS is_affiliate boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS claimed_at timestamptz;

ALTER TABLE public.species
  ADD COLUMN IF NOT EXISTS care_source_label text,
  ADD COLUMN IF NOT EXISTS care_source_url text,
  ADD COLUMN IF NOT EXISTS care_reviewed_on date,
  ADD COLUMN IF NOT EXISTS care_confidence text NOT NULL DEFAULT 'unreviewed',
  ADD COLUMN IF NOT EXISTS conspecific_strategy text NOT NULL DEFAULT 'unreviewed',
  ADD COLUMN IF NOT EXISTS conspecific_sex_ratio_note text,
  ADD COLUMN IF NOT EXISTS conspecific_notes text;

ALTER TABLE public.species
  ADD CONSTRAINT species_care_confidence_check
    CHECK (care_confidence IN ('unreviewed', 'low', 'medium', 'high')),
  ADD CONSTRAINT species_conspecific_strategy_check
    CHECK (conspecific_strategy IN ('unreviewed', 'solitary', 'pair', 'harem', 'shoal', 'colony', 'territorial'));

CREATE TABLE IF NOT EXISTS public.waitlist_signups (
  email text PRIMARY KEY,
  source text NOT NULL DEFAULT 'account-saving',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.shop_outbound_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id uuid REFERENCES public.aquarium_shops(id) ON DELETE CASCADE,
  destination text NOT NULL CHECK (destination IN ('website', 'affiliate', 'map', 'claim')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.score_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  verdict text NOT NULL CHECK (verdict IN ('safe', 'risky', 'do-not-stock')),
  issue_codes text[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.contact_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL,
  topic text NOT NULL,
  message text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.waitlist_signups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shop_outbound_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.score_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_requests ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.join_account_waitlist(p_email text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_email text := lower(trim(p_email));
BEGIN
  IF v_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' THEN
    RAISE EXCEPTION 'Enter a valid email address';
  END IF;
  INSERT INTO public.waitlist_signups(email)
  VALUES (v_email)
  ON CONFLICT (email) DO NOTHING;
END;
$$;

CREATE OR REPLACE FUNCTION public.record_shop_outbound(p_shop_id uuid, p_destination text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF p_destination NOT IN ('website', 'affiliate', 'map', 'claim') THEN
    RAISE EXCEPTION 'Unsupported destination';
  END IF;
  INSERT INTO public.shop_outbound_events(shop_id, destination)
  VALUES (p_shop_id, p_destination);
END;
$$;

CREATE OR REPLACE FUNCTION public.record_score_event(p_verdict text, p_issue_codes text[])
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF p_verdict NOT IN ('safe', 'risky', 'do-not-stock') THEN
    RAISE EXCEPTION 'Unsupported verdict';
  END IF;
  INSERT INTO public.score_events(verdict, issue_codes)
  VALUES (p_verdict, COALESCE(p_issue_codes, '{}'));
END;
$$;

CREATE OR REPLACE FUNCTION public.submit_contact_request(p_email text, p_topic text, p_message text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_email text := lower(trim(p_email));
  v_topic text := trim(p_topic);
  v_message text := trim(p_message);
BEGIN
  IF v_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' THEN
    RAISE EXCEPTION 'Enter a valid email address';
  END IF;
  IF length(v_topic) < 3 OR length(v_topic) > 80 OR length(v_message) < 10 OR length(v_message) > 4000 THEN
    RAISE EXCEPTION 'Check the topic and message length';
  END IF;
  INSERT INTO public.contact_requests(email, topic, message)
  VALUES (v_email, v_topic, v_message);
END;
$$;

REVOKE ALL ON public.waitlist_signups, public.shop_outbound_events, public.score_events, public.contact_requests FROM anon, authenticated;
REVOKE ALL ON FUNCTION public.join_account_waitlist(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.record_shop_outbound(uuid, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.record_score_event(text, text[]) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.submit_contact_request(text, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.join_account_waitlist(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.record_shop_outbound(uuid, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.record_score_event(text, text[]) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.submit_contact_request(text, text, text) TO anon, authenticated;
