insert into public.aquarium_shops (slug,name,city,region,country_code,website,specialties,description,ownership,independent_note,sells_online,ships_live_fish,pickup_only,search_url_template,delivery_reviewed_on)
select slug,name,city,region,cc,web,array['freshwater fish','filtration'],
 'Independent aquarium shop in '||city||', listing live freshwater fish and filtration gear on its own website.',
 'independent', coalesce(note,'Sells from one shop under its own name with no chain branding.'),
 true, ship, not ship, web||sfx, '2026-09-20'
from (values
('monster-aquarium-queens','Monster Aquarium','Queens','NY','US','https://www.monsteraquariumonline.com',null,false,'/search?q={q}'),
('the-waterfront-slc-salt-lake-city','The Waterfront SLC','Salt Lake City','UT','US','https://www.thewaterfrontslc.com',null,false,'/search?q={q}'),
('discover-aquatics-shop-taylor-mill','Discover Aquatics Shop','Taylor Mill','KY','US','https://discoveraquaticsshop.com',null,false,'/search?q={q}'),
('something-fishy-tropicals-oviedo','Something Fishy Tropicals','Oviedo','FL','US','https://www.somethingfishytropicals.com',null,false,'/search?q={q}'),
('aquatic-arts-brownsburg','Aquatic Arts','Brownsburg','IN','US','https://aquaticarts.com',null,true,'/search?q={q}'),
('exotic-aquarium-sacramento','Exotic Aquarium','Sacramento','CA','US','https://exoticaquarium.shop','Describes itself as a family run business.',false,'/search?q={q}'),
('big-fish-aquarium-chicago','Big Fish Aquarium','Chicago','IL','US','https://www.bigfishaquarium.com',null,true,'/search?q={q}'),
('aquatica-aquarium-gallery-valley-city','Aquatica Aquarium Gallery','Valley City','OH','US','https://shop.aquaticasuperstore.com',null,false,'/search?q={q}'),
('squeaky-s-aquatics-lawrenceville','Squeaky''s Aquatics','Lawrenceville','GA','US','https://squeakysaquatics.com','Describes itself as a family run business.',false,'/search?q={q}'),
('fish-world-aquarium-cincinnati','Fish World Aquarium','Cincinnati','OH','US','https://fishworld-aquarium.com','Describes itself as a family run business.',false,'/search?q={q}'),
('flip-aquatics-warren','Flip Aquatics','Warren','OH','US','https://flipaquatics.com',null,true,'/search?q={q}'),
('natural-environment-aquatix-jacksonville','Natural Environment Aquatix','Jacksonville','FL','US','https://naturalenvironmentaquatix.com',null,true,'/search?type=product&q={q}'),
('trins-tropical-fish-lewis-center','Trins Tropical Fish','Lewis Center','OH','US','https://trinsfish.com',null,false,'/search.php?search_query={q}'),
('the-ifish-store-richmond-hill','The iFISH Store','Richmond Hill','NY','US','https://theifishstore.com',null,true,'/search?q={q}'),
('cuboid-nature-aquarium-pipersville','Cuboid Nature Aquarium','Pipersville','PA','US','https://cuboidstore.com','Describes itself as a small local business.',true,'/search?q={q}'),
('fishy-bizz-farmington','Fishy Bizz','Farmington','MI','US','https://www.thefishybizz.com',null,false,'/?s={q}&post_type=product'),
('aqua-imports-boulder','Aqua Imports','Boulder','CO','US','https://www.aqua-imports.com','States its own founding year as a single shop.',true,'/?s={q}&post_type=product'),
('trop-aquarium-las-vegas','Trop Aquarium','Las Vegas','NV','US','https://tropaquarium.us',null,false,'/search?q={q}'),
('coachella-valley-aquatics-indio','Coachella Valley Aquatics','Indio','CA','US','https://cvafish.com',null,false,'/?s={q}&post_type=product'),
('school-of-fish-wilbraham','School of Fish','Wilbraham','MA','US','https://schooloffishinc.com','Describes itself as a small local business.',true,'/search?q={q}'),
('age-of-aquariums-cookeville','Age of Aquariums','Cookeville','TN','US','https://ageofaquariumsstores.com','Describes itself as a family run business.',true,'/search?q={q}'),
('j-y-aquarium-las-vegas','J&Y Aquarium','Las Vegas','NV','US','https://www.jyaquarium.com',null,false,'/?s={q}&post_type=product'),
('nature-aquariums-usa-lauderhill','Nature Aquariums USA','Lauderhill','FL','US','https://natureaquariums.com','States its own founding year as a single shop.',false,'/search?q={q}'),
('blue-fish-aquarium-grandville','Blue Fish Aquarium','Grandville','MI','US','https://bluefishaquarium.com',null,false,'/search?q={q}'),
('kg-tropicals-dale-city','KG Tropicals','Dale City','VA','US','https://www.kgtropicals.com',null,false,'/search?q={q}'),
('congressional-aquarium-rockville','Congressional Aquarium','Rockville','MD','US','https://congressionalaquarium.com',null,false,'/?s={q}&post_type=product'),
('aquatropics-london','AquaTropics','London','ENG','GB','https://aquatropics.co.uk','Describes itself as a family run business.',true,'/catalogsearch/result/?q={q}'),
('aquatics-unlimited-greenfield','Aquatics Unlimited','Greenfield','WI','US','https://aquaticsunlimited.com','Describes itself as a family run business.',false,'/?controller=search&s={q}'),
('coral-reef-aquatics-glasgow','Coral Reef Aquatics','Glasgow','SCT','GB','https://www.coralreefaquatics.co.uk',null,false,'/search?q={q}'),
('aquarium-adventures-sheffield','Aquarium Adventures','Sheffield','ENG','GB','https://www.aquariumadventures.co.uk',null,false,'/?s={q}&post_type=product'),
('aquatic-design-centre-london','Aquatic Design Centre','London','ENG','GB','https://aquaticdesign.co.uk',null,false,'/?s={q}&post_type=product'),
('delta-aquarium-birmingham','Delta Aquarium','Birmingham','ENG','GB','https://deltaaquarium.co.uk',null,false,'/?s={q}&post_type=product'),
('kirkys-koi-boston','Kirkys Koi','Boston','ENG','GB','https://kirkyskoi.co.uk','Describes itself as a family run business.',false,'/?controller=search&s={q}'),
('online-aquatic-store-west-hallam','Online Aquatic Store','West Hallam','ENG','GB','https://www.onlineaquaticstore.co.uk',null,true,'/search?q={q}'),
('horizon-aquatics-newton-aycliffe','Horizon Aquatics','Newton Aycliffe','ENG','GB','https://www.horizonaquatics.co.uk',null,false,'/catalogsearch/result/?q={q}'),
('the-fish-room-stockport','The Fish Room','Stockport','ENG','GB','https://www.fishroom.co.uk',null,false,'/?s={q}&post_type=product'),
('riverpark-aquatics-paisley','Riverpark Aquatics','Paisley','SCT','GB','https://riverparkaquatics.co.uk',null,false,'/search.php?search_query={q}'),
('wharf-aquatics-pinxton','Wharf Aquatics','Pinxton','ENG','GB','https://wharfaquatics.co.uk','Describes itself as independently owned.',false,'/search?q={q}'),
('premier-aquatics-runcorn','Premier Aquatics','Runcorn','ENG','GB','https://www.premieraquatics.co.uk','Describes itself as independently owned.',false,'/search?q={q}'),
('tropical-fish-co-london','Tropical Fish Co','London','ENG','GB','https://tropicalfishco.co.uk',null,true,'/search?q={q}'),
('star-fisheries-st-marys-bay','Star Fisheries','St Marys Bay','ENG','GB','https://www.starfisheries.co.uk',null,false,'/?s={q}&post_type=product'),
('east-ocean-aquatic-singapore','East Ocean Aquatic','Singapore',null,'SG','https://eastoceansg.com',null,false,'/search?q={q}'),
('top-aquatics-petaling-jaya','Top Aquatics','Petaling Jaya','Selangor','MY','https://www.aquariumshop.com.my',null,false,'/?s={q}&post_type=product'),
('fishyhub-singapore','FishyHub','Singapore',null,'SG','https://fishyhub.com',null,false,'/?s={q}&post_type=product'),
('tropical-supplies-wheatley-hill','Tropical Supplies','Wheatley Hill','ENG','GB','https://tropical-supplies.co.uk',null,false,'/search?q={q}'),
('the-aquatic-store-bristol-bristol','The Aquatic Store Bristol','Bristol','ENG','GB','https://www.theaquaticstoreonline.co.uk',null,false,'/?s={q}&post_type=product'),
('jzxonline-singapore','JZXonline','Singapore','Clementi','SG','https://jzxonline.com',null,false,'/search?q={q}'),
('myaquariumshops-johor-bahru','MyAquariumshops','Johor Bahru','Johor','MY','https://www.myaquariumshops.com.my',null,true,'/search?q={q}'),
('shirley-aquatics-wythall','Shirley Aquatics','Wythall','ENG','GB','https://shirleyaquatics.co.uk',null,false,'/search?q={q}'),
('veda-aquarium-bangalore','Veda Aquarium','Bangalore','Karnataka','IN','https://vedaaquarium.com',null,false,'/?s={q}&post_type=product'),
('sirena-aquatics-san-pedro','Sirena Aquatics','San Pedro','Laguna','PH','https://sirenaaquatics.ph','Describes itself as a family run business.',false,'/search?q={q}'),
('greenflow-hong-kong','GreenFlow','Hong Kong',null,'HK','https://www.greenflow.hk',null,false,'/search?q={q}'),
('aquarium-enjoy-bangkok','Aquarium Enjoy','Bangkok',null,'TH','https://aquariumenjoy.com',null,false,'/search?q={q}'),
('april-s-aquarium-vancouver','April''s Aquarium','Vancouver','BC','CA','https://yourlocalfishstore.com','Describes itself as a family run business.',false,'/search?q={q}'),
('aquashop-bursa','Aquashop','Bursa',null,'TR','https://www.aquashop.com.tr',null,false,'/?s={q}&post_type=product'),
('pisces-pets-calgary','Pisces Pets','Calgary','AB','CA','https://piscespets.com',null,false,'/search?q={q}'),
('epp-n-flow-aquariums-ottawa','Epp n Flow Aquariums','Ottawa','ON','CA','https://www.eppnflow.com',null,false,'/search?q={q}'),
('the-beastiary-toronto','The Beastiary','Toronto','ON','CA','https://thebeastiary.ca',null,false,'/search?q={q}'),
('apex-aquatic-collingwood','Apex Aquatic','Collingwood','VIC','AU','https://apexaquatic.com.au',null,false,'/search?q={q}'),
('tropical-aquarium-hamilton','Tropical Aquarium','Hamilton','QLD','AU','https://tropicalaquarium.com.au',null,false,'/search?q={q}'),
('arc-aquariums-hornsby','ARC Aquariums','Hornsby','NSW','AU','https://arcaquariums.com','Describes itself as a family run business.',false,'/search?q={q}'),
('newtown-aquarium-newtown','Newtown Aquarium','Newtown','NSW','AU','https://newtownaquarium.com.au',null,true,'/catalogsearch/result/?q={q}'),
('boutique-aquanova-la-prairie','Boutique AquaNova','La Prairie','QC','CA','https://www.boutiqueaquanova.com',null,false,'/search?q={q}'),
('famous-pets-dubai','Famous Pets','Dubai',null,'AE','https://famouspets.ae',null,false,'/?controller=search&s={q}'),
('aggies-aquariums-pooraka','Aggies Aquariums','Pooraka','SA','AU','https://aggiesaquariums.com.au',null,false,'/?controller=search&s={q}'),
('kings-of-the-aquarium-old-beach','Kings Of The Aquarium','Old Beach','TAS','AU','https://www.kingsoftheaquarium.com.au',null,false,'/?s={q}&post_type=product'),
('the-aquarium-shop-gold-coast','The Aquarium Shop','Gold Coast','QLD','AU','https://www.theaquariumshop.com.au','Describes itself as a family run business.',false,'/?s={q}&post_type=product'),
('benny-s-aquarium-bundall','Benny''s Aquarium','Bundall','QLD','AU','https://bennysaquarium.com',null,false,'/search?q={q}'),
('otago-petfoods-dunedin','Otago Petfoods','Dunedin','OTA','NZ','https://otagopetfoods.co.nz','Describes itself as a small local business.',false,'/search?q={q}'),
('js-aquarios-manaus','JS Aquarios','Manaus','AM','BR','https://jsaquarioseutilidades.com.br',null,false,'/search?q={q}'),
('acuario-xel-ha-mexico-city','Acuario Xel-ha','Mexico City','CDMX','MX','https://acuarioxelha.mx',null,false,'/?s={q}&post_type=product'),
('aqua-stuchi-curitiba','Aqua Stuchi','Curitiba','PR','BR','https://aquastuchi.com.br',null,false,'/?controller=search&s={q}'),
('aquar-guadalajara','Aquar','Guadalajara','Jalisco','MX','https://aquar.com.mx',null,false,'/?s={q}&post_type=product'),
('top-fin-aquatics-auckland','Top Fin Aquatics','Auckland','AUK','NZ','https://www.topfinaquatics.co.nz','Describes itself as hobbyist run.',true,'/search?q={q}'),
('franco-aquarismo-sao-paulo','Franco Aquarismo','Sao Paulo','SP','BR','https://www.francoaquarismo.com.br',null,false,'/?s={q}&post_type=product'),
('legacy-aquatics-auckland','Legacy Aquatics','Auckland','AUK','NZ','https://legacyaquatics.co.nz',null,false,'/?s={q}&post_type=product'),
('la-bodega-de-los-peces-cali','La Bodega de los Peces','Cali','Valle del Cauca','CO','https://bodegadelospeces.com',null,false,'/search?q={q}'),
('big-fish-santiago','Big Fish','Santiago','Nunoa','CL','https://www.bigfish.cl',null,false,'/search?q={q}'),
('amazonicos-pet-bogota','Amazonicos PET','Bogota','DC','CO','https://amazonicospet.com',null,false,'/search?q={q}'),
('acuario-planet-chiclayo','Acuario Planet','Chiclayo','Lambayeque','PE','https://acuarioplanet.com',null,false,'/search?q={q}'),
('acuatica-peru-lima','Acuatica Peru','Lima',null,'PE','https://www.acuaticaperu.com',null,false,'/?s={q}&post_type=product'),
('pezera-acuario-medellin','PEZera Acuario','Medellin','Antioquia','CO','https://www.pezeraacuario.com',null,false,'/?s={q}&post_type=product'),
('zierfische-online-com-hechingen','Zierfische-Online.com','Hechingen',null,'DE','https://zierfische-online.com','States it is a family run business (Familienbetrieb).',false,'/search?q={q}'),
('interaquaristik-biedenkopf','Interaquaristik','Biedenkopf',null,'DE','https://www.interaquaristik.de',null,false,'/search?q={q}'),
('starfish-aquaria-heemstede','StarFish Aquaria','Heemstede',null,'NL','https://starfishaquaria.nl',null,false,'/?s={q}&post_type=product'),
('elysium-aquarium-auvelais','Elysium Aquarium','Auvelais',null,'BE','https://elysium-aquarium.be',null,false,'/search?q={q}'),
('akv-ria-aquascape-prague','Akvária Aquascape','Prague',null,'CZ','https://www.akvaria-aquascape.cz',null,false,'/vyhledavani/?string={q}'),
('bioacuarios-chiclana-de-la-frontera','BioAcuarios','Chiclana de la Frontera',null,'ES','https://www.bioacuarios.com',null,false,'/?s={q}&post_type=product'),
('catfish-szczecin','Catfish','Szczecin',null,'PL','https://catfish.sklep.pl',null,false,'/?s={q}&post_type=product'),
('euskaltropik-san-sebasti-n','Euskaltropik','San Sebastián',null,'ES','https://www.euskaltropik.com','States it is a family business (empresa familiar).',false,'/module/iqitsearch/searchiqit?s={q}'),
('aquaverso-aveiro','Aquaverso','Aveiro',null,'PT','https://www.aquaverso.pt',null,false,'/search?q={q}'),
('alias-acquari-quarto','Alias Acquari','Quarto',null,'IT','https://www.aliasacquari.it',null,false,'/?s={q}&post_type=product'),
('ecoarium-vila-nova-de-gaia','Ecoarium','Vila Nova de Gaia',null,'PT','https://www.ecoarium.pt',null,false,'/module/iqitsearch/searchiqit?s={q}'),
('aquarium-dani-parets-del-vall-s','Aquarium Dani','Parets del Vallès',null,'ES','https://aquariumdani.com',null,false,'/?s={q}&post_type=product'),
('fyns-akvarie-centrum-odense','Fyns Akvarie Centrum','Odense',null,'DK','https://www.fynsakvariecentrum.dk',null,false,'/?s={q}&post_type=product'),
('cyberzoo-trollh-ttan','CyberZoo','Trollhättan',null,'SE','https://www.cyberzoo.se',null,false,'/?s={q}&post_type=product')
) as v(slug,name,city,region,cc,web,note,ship,sfx)
on conflict (slug) do nothing;