-- Global independent shops directory data, applied 2026-09-20.
-- Schema for the new columns lives in drizzle/migrations/0007_shops_global_independent_directory.sql.
-- Every shop below was checked against the shop's own website on the date recorded in
-- delivery_reviewed_on. Where delivery_reviewed_on is NULL we could not confirm live fish
-- delivery, so the app says so rather than guessing. search_url_template values were each
-- tested with a live search for "tetra" and returned product results.

UPDATE public.aquarium_shops SET ownership = 'chain' WHERE slug = 'petbarn-generic-au';

UPDATE public.aquarium_shops SET sells_online = true, search_url_template = 'https://amazingamazon.com.au/search?q={q}' WHERE slug = 'amazing-amazon-sydney';
UPDATE public.aquarium_shops SET sells_online = true, search_url_template = 'https://coburgaquarium.com.au/search?q={q}' WHERE slug = 'coburg-aquarium';
UPDATE public.aquarium_shops SET sells_online = true, search_url_template = 'https://thetechden.com.au/search?q={q}' WHERE slug = 'the-tech-den-brisbane';
UPDATE public.aquarium_shops SET sells_online = true, ships_live_fish = true, ships_to_countries = '{AU}', shipping_note = 'They state Australia-wide live fish delivery.', city = 'National', region = NULL WHERE slug = 'livefish-online';
UPDATE public.aquarium_shops SET independent_note = 'Single independent store, not part of a chain.' WHERE independent_note IS NULL AND ownership = 'independent';

INSERT INTO public.aquarium_shops
  (slug, name, city, region, country_code, suburb, state, website, phone, specialties, description, ownership, independent_note, sells_online, ships_live_fish, pickup_only, ships_to_countries, ships_to_regions, shipping_note, delivery_reviewed_on, search_url_template)
VALUES
  ('grosvenor-tropicals-lisburn','Grosvenor Tropicals','Lisburn','NI','GB','Lisburn','NI','https://grosvenor-tropicals.co.uk',NULL,'{marine,pond,imports}','A long-running family aquatic shop in Lisburn with its own quarantine facility.','independent','Family run business founded in 1969, stated on their own site.',true,false,false,'{}','{}',NULL,NULL,'https://grosvenor-tropicals.co.uk/?s={q}&post_type=product'),
  ('byrkley-aquatics','Byrkley Aquatics','Burton upon Trent','ENG','GB','Burton upon Trent','ENG','https://byrkleyaquatics.co.uk','01283 712924','{planted,aquascaping,tropical}','A family run aquascaping and tropical fish specialist in the Midlands.','independent','Describes itself as a trusted family business of 40 years.',true,false,false,'{}','{}',NULL,NULL,'https://byrkleyaquatics.co.uk/search?q={q}'),
  ('wholesale-tropicals-london','Wholesale Tropicals','London','ENG','GB','Bethnal Green','ENG','https://wholesaletropicalsaquatics.co.uk','020 7739 5356','{tropical,planted,freshwater}','A long established family run freshwater fish shop in east London.','independent','Family run aquarium fish shop trading in Bethnal Green for over 50 years.',true,false,true,'{}','{}','Walk-in shop, no live fish posted.',NULL,'https://wholesaletropicalsaquatics.co.uk/?s={q}&post_type=product'),
  ('repxotics-shepton-mallet','Repxotics','Shepton Mallet','ENG','GB','Shepton Mallet','ENG','https://www.repxotics.co.uk','01749 937340','{"tropical fish",exotics,reptiles}','A Somerset shop selling tropical fish alongside reptiles and exotics.','independent','Long established family run independent specialist, stated on their site.',true,false,true,'{}','{}','Walk-in shop, no live fish posted.',NULL,'https://www.repxotics.co.uk/?s={q}&post_type=product'),
  ('pet-zone-san-diego','Pet Zone Tropical Fish','San Diego','CA','US','San Diego','CA','https://www.petzonesd.com',NULL,'{freshwater,planted,plecos}','A San Diego shop specialising only in freshwater fish and planted tanks.','independent','Single freshwater-only San Diego store, trading since 2007.',true,false,false,'{}','{}',NULL,NULL,'https://www.petzonesd.com/search.php?search_query={q}'),
  ('wild-fish-aquarium-brampton','Wild Fish Aquarium','Brampton','ON','CA','Brampton','ON','https://wildfishaquarium.ca',NULL,'{planted,freshwater,community}','An independent family owned aquarium shop in downtown Brampton.','independent','Their about page states an independent family-owned business established in 2012.',true,false,false,'{}','{}',NULL,NULL,'https://wildfishaquarium.ca/?s={q}&post_type=product'),
  ('aquarium-coenen-best','Aquarium Coenen','Best','NB','NL','Best','NB','https://aquariumcoenen.nl',NULL,'{"family run",community,plants}','A long running Dutch family aquarium shop and showroom.','independent','Family business (familiebedrijf) since 1961, stated on their own site.',true,false,false,'{}','{}',NULL,NULL,'https://aquariumcoenen.nl/?s={q}&post_type=product'),
  ('aquariumgek','Aquariumgek','Netherlands',NULL,'NL',NULL,NULL,'https://aquariumgek.nl',NULL,'{freshwater,imports,quarantine}','A small Dutch shop stocking hundreds of freshwater species from its own imports.','independent','Owner-run shop that grew out of the owner''s own fishkeeping, with its own quarantine.',true,false,false,'{}','{}',NULL,NULL,'https://aquariumgek.nl/?s={q}&post_type=product'),
  ('aquariumvissenwinkel-beilen','Aquariumvissenwinkel','Beilen','DR','NL','Beilen','DR','https://aquariumvissenwinkel.nl','0593 541415','{cichlids,livebearers,shrimp}','A Dutch fish shop delivering freshwater fish across the Netherlands and Belgium.','independent','Small owner-run shop offering free pickup in Beilen.',true,true,false,'{NL,BE}','{}','Their site states home delivery of fish within the Netherlands and Belgium, with pickup in Beilen.','2026-09-20','https://aquariumvissenwinkel.nl/?s={q}&post_type=product'),
  ('fishlist-sg','Fishlist','Singapore',NULL,'SG',NULL,NULL,'https://fishlist.com.sg',NULL,'{shrimp,guppies,tetras}','A Singapore online shop run by one keeper, specialising in shrimp and small fish.','independent','Run by a named individual owner rather than a retail group.',true,false,false,'{}','{}',NULL,NULL,'https://fishlist.com.sg/search?q={q}'),
  ('aquatic-avenue-sg','Aquatic Avenue','Singapore',NULL,'SG',NULL,NULL,'https://aquaticavenueonline.com',NULL,'{aquascaping,planted,"custom tanks"}','A Singapore aquascaping and livestock shop known for custom aquarium builds.','independent','Single Singapore store combining aquascapes, livestock and hardware.',true,false,false,'{}','{}',NULL,NULL,'https://aquaticavenueonline.com/search?q={q}'),
  ('simply-fish-nz','Simply Fish','New Zealand',NULL,'NZ',NULL,NULL,'https://simplyfish.co.nz',NULL,'{plants,"locally bred",servicing}','A small New Zealand business offering locally bred fish, plants and tank servicing.','independent','Small owner-operated business, not part of a retail group.',true,false,false,'{}','{}',NULL,NULL,'https://simplyfish.co.nz/search?q={q}'),
  ('aqua-house-christchurch','Aqua House','Christchurch',NULL,'NZ','Christchurch',NULL,'https://aquahouse.co.nz',NULL,'{planted,reef,terrarium}','A Christchurch aquarium shop with a showroom, shipping supplies nationwide.','independent','States it is a fully New Zealand operated business with no drop-shipping.',true,false,false,'{}','{}','They ship dry goods and plants nationwide. Live fish delivery is not stated.','2026-09-20','https://aquahouse.co.nz/search?q={q}'),
  ('allfish2u-sydney','AllFish2U','Sydney','NSW','AU','Sydney','NSW','https://allfish2u.au',NULL,'{natives,killifish,cichlids}','A Sydney freshwater shop with wild caught and rarely seen species.','independent','Single Sydney freshwater store, not part of a chain.',true,true,false,'{AU}','{}','They state live fish freight within Australia. Check current freight rules for your state.','2026-09-20','https://allfish2u.au/?s={q}&post_type=product'),
  ('the-fish-farm-au','The Fish Farm','Australia',NULL,'AU',NULL,NULL,'https://thefishfarm.com.au','0409 337 418','{livebearers,"farm bred",freight}','An Australian fish farm sending its own bred livestock direct to customers.','independent','Owner-run fish farm selling its own stock direct.',true,true,false,'{AU}','{}','They state flat-rate courier despatch early in the week, Australia-wide.','2026-09-20','https://thefishfarm.com.au/search?q={q}'),
  ('school-of-scape-perth','School Of Scape','Kenwick','WA','AU','Kenwick','WA','https://schoolofscape.com.au',NULL,'{planted,aquascaping,"rare plants"}','A Perth aquascaping shop with a gallery space, selling plants and fish online.','independent','Single Perth gallery and shop, independently run.',true,true,false,'{AU}','{}','They state online fish and plant sales across Australia. Check current freight rules for your state.','2026-09-20','https://schoolofscape.com.au/search?q={q}'),
  ('aquaristic-online-sydney','Aquaristic Online','Rosebery','NSW','AU','Rosebery','NSW','https://www.aquaristiconline.com.au',NULL,'{marine,cichlids,reef}','A Sydney shop selling marine and freshwater livestock, with pickup in store.','independent','Single Sydney store with a named owner and walk-in pickup.',true,true,false,'{AU}','{}','They state national livestock delivery with store pickup available.','2026-09-20','https://www.aquaristiconline.com.au/search?q={q}')
ON CONFLICT (slug) DO NOTHING;
