-- Pea puffer and freshwater stingrays, requested 2026-09-20.
-- All care values are from published sources; source and review date ship on each row.
-- Pea puffer: Seriously Fish (tank 60x30x30 cm, pH 6.0-7.5, 24-28 C, intolerant fin-nipper).
-- Motoro ray: Seriously Fish (base 240x90 cm min, pH 6.0-7.5, 24-28 C, ~35 cm disc).
-- Leopoldi ray: Seriously Fish (Rio Xingu, warm 26-30 C, pH 5.5-7.0, ~40 cm disc).

insert into public.species (common_name, scientific_name, min_tank_litres, adult_size_cm, bioload_factor, swim_zone, temperament, is_schooling, min_group_size, fin_nipper, predatory, long_finned, active, native_ph_min, native_ph_max, native_temp_min_c, native_temp_max_c, biotope_region, native_habitat_type, legal_in_australia, legal_status, care_source_label, care_source_url, care_reviewed_on, care_confidence, conspecific_strategy, conspecific_sex_ratio_note, conspecific_notes) values
('Pea puffer','Carinotetraodon travancoricus',54,2.5,1.0,'mid','aggressive',false,1,true,true,false,true,6.0,7.5,24,28,'south_asian_river','sluggish heavily vegetated inland waters',true,'permitted','Seriously Fish','https://www.seriouslyfish.com/species/carinotetraodon-travancoricus','2026-09-20','high','territorial','A single puffer works; in a group, keep one male with two or more females','Best kept alone or in a group large enough to spread squabbles, with dense planting to break sight lines'),
('Ocellate river stingray','Potamotrygon motoro',1000,35,8.0,'bottom','peaceful',false,1,false,true,false,true,6.0,7.5,24,28,'south_american_river','slow rivers and floodplain lakes',true,'permitted','Seriously Fish','https://www.seriouslyfish.com/species/potamotrygon-motoro','2026-09-20','medium','unreviewed',null,'Needs a tank with a base of at least 240 x 90 cm and a soft sand substrate; will eat any fish small enough to swallow'),
('Xingu river stingray','Potamotrygon leopoldi',1000,40,10.0,'bottom','peaceful',false,1,false,true,false,true,5.5,7.0,26,30,'south_american_river','sandy savannah rivers',true,'permitted','Seriously Fish','https://www.seriouslyfish.com/species/potamotrygon-leopoldi','2026-09-20','medium','unreviewed',null,'From the warm, fast, oxygen-rich Rio Xingu; needs the same very large footprint, strong flow and pristine water as other large rays');
