/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopsIndexRouteImport } from './routes/shops.index'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as TSlugRouteImport } from './routes/t.$slug'
import { Route as SpeciesIdRouteImport } from './routes/species.$id'
import { Route as ShopsSlugRouteImport } from './routes/shops.$slug'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsIndexRoute = ShopsIndexRouteImport.update({
  id: '/shops/',
  path: '/shops/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeciesIdRoute = SpeciesIdRouteImport.update({
  id: '/species/$id',
  path: '/species/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsSlugRoute = ShopsSlugRouteImport.update({
  id: '/shops/$slug',
  path: '/shops/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/quiz': typeof QuizRoute
  '/saved': typeof SavedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/shops/$slug': typeof ShopsSlugRoute
  '/species/$id': typeof SpeciesIdRoute
  '/t/$slug': typeof TSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/shops/': typeof ShopsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/quiz': typeof QuizRoute
  '/saved': typeof SavedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/shops/$slug': typeof ShopsSlugRoute
  '/species/$id': typeof SpeciesIdRoute
  '/t/$slug': typeof TSlugRoute
  '/blog': typeof BlogIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/shops': typeof ShopsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/quiz': typeof QuizRoute
  '/saved': typeof SavedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/shops/$slug': typeof ShopsSlugRoute
  '/species/$id': typeof SpeciesIdRoute
  '/t/$slug': typeof TSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/shops/': typeof ShopsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/quiz'
    | '/saved'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/guides/$slug'
    | '/shops/$slug'
    | '/species/$id'
    | '/t/$slug'
    | '/blog/'
    | '/guides/'
    | '/shops/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/quiz'
    | '/saved'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/guides/$slug'
    | '/shops/$slug'
    | '/species/$id'
    | '/t/$slug'
    | '/blog'
    | '/guides'
    | '/shops'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/mcp'
    | '/quiz'
    | '/saved'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/guides/$slug'
    | '/shops/$slug'
    | '/species/$id'
    | '/t/$slug'
    | '/blog/'
    | '/guides/'
    | '/shops/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McpRoute: typeof McpRoute
  QuizRoute: typeof QuizRoute
  SavedRoute: typeof SavedRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  BlogSlugRoute: typeof BlogSlugRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  ShopsSlugRoute: typeof ShopsSlugRoute
  SpeciesIdRoute: typeof SpeciesIdRoute
  TSlugRoute: typeof TSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  ShopsIndexRoute: typeof ShopsIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/': {
      id: '/shops/'
      path: '/shops'
      fullPath: '/shops/'
      preLoaderRoute: typeof ShopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/species/$id': {
      id: '/species/$id'
      path: '/species/$id'
      fullPath: '/species/$id'
      preLoaderRoute: typeof SpeciesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$slug': {
      id: '/shops/$slug'
      path: '/shops/$slug'
      fullPath: '/shops/$slug'
      preLoaderRoute: typeof ShopsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McpRoute: McpRoute,
  QuizRoute: QuizRoute,
  SavedRoute: SavedRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  BlogSlugRoute: BlogSlugRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  ShopsSlugRoute: ShopsSlugRoute,
  SpeciesIdRoute: SpeciesIdRoute,
  TSlugRoute: TSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  ShopsIndexRoute: ShopsIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
