-- Seed the invertebrate catalogue: shrimp, snails, crayfish and freshwater crabs.
--
-- Every row cites the care source used for its minimum tank, group size,
-- temperament, adult size and water range in care_source_url. bioload_factor is a
-- modelling estimate relative to fish, not a sourced figure, and stays conservative.
-- care_confidence is 'low' until each row has a second reviewer.
--
-- Safe to re-run: a row is only inserted when no invertebrate with the same
-- scientific name exists.

WITH new_inverts (common_name, scientific_name, invert_group, min_tank_litres, adult_size_cm, bioload_factor, temperament, min_group_size, predatory, fish_risk_note, native_ph_min, native_ph_max, native_temp_min_c, native_temp_max_c, biotope_region, algae_role, care_notes, care_source_label, care_source_url) AS (
  VALUES
('Cherry shrimp', 'Neocaridina davidi', 'shrimp', 20, 4, 0.03, 'peaceful', 10, false, 'Most fish over 5 cm will eat small shrimp.', 6.5, 8.0, 18, 28, 'east_asian_stream', 'Grazes biofilm and soft algae', 'Breeds readily in stable, mature planted tanks.', 'Tropical Fish Co care guide (Neocaridina davidi)', 'https://tropicalfishco.co.uk/care-guides/cherry-shrimp'),
('Crystal red shrimp', 'Caridina cantonensis', 'shrimp', 30, 3, 0.03, 'peaceful', 10, false, 'Most fish over 5 cm will eat small shrimp.', 5.8, 6.8, 20, 24, 'east_asian_stream', 'Grazes biofilm and soft algae', 'Needs soft, acidic, stable water over active soil; best kept species-only.', 'Fin & Stem care guide (Caridina cantonensis CRS)', 'https://finandstem.com/shrimp/crystal-red-shrimp'),
('Amano shrimp', 'Caridina multidentata', 'shrimp', 40, 3.5, 0.04, 'peaceful', 5, false, 'Most fish over 8 cm may eat small shrimp; amano usually outgrow the risk.', 6.5, 7.5, 18, 28, 'east_asian_stream', 'Heavy grazer of hair algae and biofilm', 'Larvae need brackish water so it almost never breeds in home tanks.', 'Fin & Stem care guide (Caridina multidentata)', 'https://finandstem.com/shrimp/amano-shrimp'),
('Babaulti shrimp', 'Caridina babaulti', 'shrimp', 20, 3.5, 0.03, 'peaceful', 5, false, 'Most fish over 5 cm will eat small shrimp.', 6.5, 7.8, 20, 26, 'south_asian_river', 'Grazes soft algae and biofilm', 'Shyer than Neocaridina; appreciates dense planting and hiding places.', 'Shrimpcent care guide (Caridina cf. babaulti)', 'https://shrimpcent.com/en/species/babaulti-shrimp'),
('Bamboo shrimp', 'Atyopsis moluccensis', 'shrimp', 80, 8, 0.08, 'peaceful', 1, false, 'Puffers, large cichlids and loaches will attack this shrimp.', 6.5, 7.5, 22, 28, 'se_asian_stream', NULL, 'Filter-feeds from current with fan-like appendages; will starve in a spotless, still tank.', 'Aquatic-Art care guide (Atyopsis moluccensis)', 'https://www.aquatic-art.com/fish/bamboo-shrimp'),
('Vampire shrimp', 'Atya gabonensis', 'shrimp', 75, 13, 0.1, 'peaceful', 1, false, 'Large or aggressive fish may harass this shrimp while it is filter-feeding or freshly moulted.', 6.5, 7.8, 24, 28, 'west_african_stream', NULL, 'Filter-feeds on suspended particles; needs strong current and will starve in an overly clean tank.', 'Wikipedia (Atya gabonensis), cross-checked with TankBud care guide', 'https://en.wikipedia.org/wiki/Atya_gabonensis'),
('Whisker shrimp', 'Macrobrachium lanchesteri', 'shrimp', 38, 6, 0.06, 'aggressive', 1, true, 'Will attack and kill small fish, dwarf shrimp and snails; often mis-sold as ghost shrimp.', 6.5, 8.0, 22, 28, 'se_asian_stream', NULL, 'A predatory Macrobrachium best kept species-only, not as a peaceful cleanup shrimp.', 'ShrimpKeepers care guide (Macrobrachium lanchesteri)', 'https://www.shrimpkeepers.com/species/whisker-shrimp/'),
('Ghost shrimp', 'Palaemonetes paludosus', 'shrimp', 19, 4, 0.03, 'peaceful', 1, false, 'Larger or predatory fish will eat this shrimp; sold as feeders for that reason.', 6.5, 8.0, 18, 28, 'north_american_freshwater', 'Grazes detritus and biofilm', 'Nearly transparent scavenger native to the south-eastern United States.', 'Guidarium care guide (Palaemonetes paludosus)', 'https://guidarium.com/fishes/ghost-shrimp'),
('Zebra nerite snail', 'Neritina natalensis', 'snail', 19, 2.5, 0.03, 'peaceful', 1, false, NULL, 7.2, 8.2, 22, 26, 'west_african_stream', 'Aggressive grazer of algae including green spot algae', 'Needs hard, alkaline water for shell health; will not breed in freshwater.', 'Fishkeeper.co.uk species profile (Neritina natalensis)', 'https://www.fishkeeper.co.uk/fish/freshwater/miscellaneous/zebra-snail'),
('Horned nerite snail', 'Clithon corona', 'snail', 20, 2, 0.03, 'peaceful', 1, false, NULL, 6.7, 8.5, 22, 27, 'se_asian_stream', 'Excellent algae and biofilm grazer', 'Small and peaceful; will not overrun a tank since it cannot breed in freshwater.', 'Glassbox Diaries care guide (Clithon corona)', 'https://glassboxdiaries.com/care_guide/clithon-corona/'),
('Mystery snail', 'Pomacea diffusa', 'snail', 20, 5, 0.06, 'peaceful', 1, false, 'Loaches, puffers and other invertebrate-eating fish may attack this snail.', 6.5, 8.0, 21, 26, 'south_american_river', 'Grazes algae, biofilm and soft plant matter', 'Breathes with both a gill and a lung, and needs an air gap under the lid.', 'TankBud care guide (Pomacea diffusa)', 'https://tankbud.com/species/mystery-snail'),
('Apple snail', 'Pomacea bridgesii', 'snail', 19, 6, 0.06, 'peaceful', 1, false, 'Loaches, puffers and other invertebrate-eating fish may attack this snail.', 7.0, 8.4, 20, 28, 'south_american_river', 'Grazes some algae, mainly biofilm and detritus', 'Needs a tight, well-ventilated lid as it periodically surfaces to breathe.', 'The Aquarium Wiki species profile (Pomacea bridgesii)', 'https://www.theaquariumwiki.com/wiki/Pomacea_bridgesii'),
('Great ramshorn snail', 'Planorbarius corneus', 'snail', 20, 4, 0.04, 'peaceful', 1, false, NULL, 6.5, 8.0, 18, 25, 'european_freshwater', 'Grazes algae, biofilm and soft plant matter', 'Uses iron-based haemoglobin, unusual among snails, helping it cope with low-oxygen water.', 'TankBud care guide (Planorbarius corneus)', 'https://tankbud.com/species/great-ramshorn'),
('Ramshorn snail', 'Planorbella duryi', 'snail', 19, 2.5, 0.03, 'peaceful', 1, false, NULL, 7.0, 8.0, 18, 28, 'north_american_freshwater', 'Grazes algae, biofilm and leftover food', 'Hermaphroditic and prolific; population size tracks feeding rate.', 'Aquendium care guide (Planorbella duryi)', 'https://aquendium.com/species/ramshorn-snail/'),
('Bladder snail', 'Physella acuta', 'snail', 20, 1.5, 0.02, 'peaceful', 1, false, NULL, 6.5, 8.0, 14, 30, 'european_freshwater', 'Grazes soft algae, diatoms and biofilm', 'Self-fertilising hermaphrodite; a single hitchhiker can found a whole population.', 'TankBud care guide (Physella acuta)', 'https://tankbud.com/species/bladder-snail'),
('Malaysian trumpet snail', 'Melanoides tuberculata', 'snail', 20, 3, 0.03, 'peaceful', 1, false, NULL, 6.5, 8.0, 18, 28, 'south_asian_river', 'Aerates substrate and consumes detritus rather than algae directly', 'Burrows through substrate by day and emerges at night; breeds parthenogenetically.', 'Fin & Stem care guide (Melanoides tuberculata)', 'https://finandstem.com/snails/malaysian-trumpet-snail'),
('Sulawesi rabbit snail', 'Tylomelania zemis', 'snail', 60, 8, 0.09, 'peaceful', 1, false, NULL, 7.0, 8.5, 24, 28, 'unmapped', 'Grazes algae and detritus', 'Ovoviviparous, giving live birth to one or two young at a time, so populations grow slowly.', 'Aquendium care guide (Tylomelania zemis)', 'https://aquendium.com/species/rabbit-snail/'),
('Assassin snail', 'Anentome helena', 'snail', 38, 2.5, 0.04, 'peaceful', 1, true, 'Hunts and eats other snails and can attack shrimp, especially during moulting.', 7.0, 8.0, 22, 27, 'se_asian_stream', NULL, 'Buries in substrate by day and hunts other snails at night; cannot be kept with other snail species.', 'Aquendium care guide (Anentome helena)', 'https://aquendium.com/species/assassin-snail/'),
('Great pond snail', 'Lymnaea stagnalis', 'snail', 19, 6, 0.05, 'peaceful', 1, false, NULL, 6.5, 8.0, 18, 24, 'european_freshwater', 'Grazes algae and biofilm, but will also eat soft live plants', 'Breathes air via a lung and surfaces regularly; breeds fast given plentiful food.', 'TankBud care guide (Lymnaea stagnalis)', 'https://tankbud.com/species/great-pond-snail'),
('Marbled limpet nerite', 'Septaria porcellana', 'snail', 20, 3, 0.03, 'peaceful', 1, false, NULL, 6.5, 8.0, 23, 28, 'se_asian_stream', 'Grazes algae, biofilm and diatoms off rock and glass', 'Flat limpet-shaped shell clamps tightly to hard surfaces in current; will not breed in freshwater.', 'TankBud care guide (Septaria porcellana)', 'https://tankbud.com/species/marbled-limpet-nerite'),
('CPO dwarf orange crayfish', 'Cambarellus patzcuarensis', 'crayfish', 30, 5, 0.12, 'peaceful', 1, true, 'May eat slow, sick or moulting shrimp and fry but is too small to threaten healthy fish.', 6.5, 8.0, 18.0, 25.5, 'central_american_river', NULL, 'Territorial toward its own kind so provide multiple caves; one of the few crayfish safe in a well-stocked planted tank.', 'Aquariadise CPO crayfish caresheet', 'https://www.aquariadise.com/caresheet-cambarellus-patzcuarensis/'),
('Cajun dwarf crayfish', 'Cambarellus shufeldtii', 'crayfish', 40, 3.5, 0.1, 'peaceful', 1, false, NULL, 5.4, 7.4, 20.0, 24.0, 'north_american_freshwater', NULL, 'Does not dig or damage plants, making it one of the most community-friendly dwarf crayfish.', 'Aquarium Breeder Cambarellus shufeldtii guide', 'https://aquariumbreeder.com/cambarellus-shufeldtii-detailed-guide-care-diet-and-breeding/'),
('Red swamp crayfish', 'Procambarus clarkii', 'crayfish', 90, 12, 0.8, 'aggressive', 1, true, 'Will attack, kill and eat fish, snails and shrimp; not to be trusted with any tankmates.', 7.0, 8.0, 22.0, 27.0, 'north_american_freshwater', NULL, 'Prolific escape artist and globally invasive species; restricted or banned in many places, never release it into the wild.', 'Aquarium Breeder Procambarus clarkii guide', 'https://aquariumbreeder.com/procambarus-clarkii-detailed-guide-care-diet-and-breeding/'),
('Electric blue crayfish', 'Procambarus alleni', 'crayfish', 120, 20, 1.3, 'aggressive', 1, true, 'Pulls fish apart in overnight attacks; not suitable for any community tank.', 6.5, 8.5, 15.0, 26.0, 'north_american_freshwater', NULL, 'Restricted in some places, so check your local rules; a strong digger and climber that needs fixed decor and a secure lid.', 'Fishkeeping.co.uk electric blue crayfish caresheet', 'https://www.fishkeeping.co.uk/modules/caresheets/caresheet.php?caresheetID=133'),
('Redclaw crayfish', 'Cherax quadricarinatus', 'crayfish', 120, 35, 1.5, 'semi-aggressive', 1, true, 'Will catch passing fish of any size at night despite a calmer adult temperament.', 7.0, 8.5, 23.0, 28.0, 'australian_native', NULL, 'Non-burrowing but a strong digger and plant destroyer; needs a large single-species tank with a secure lid.', 'Aquarium Breeder red claw crayfish guide', 'https://aquariumbreeder.com/red-claw-crayfish-detailed-guide-care-diet-and-breeding/'),
('Common yabby', 'Cherax destructor', 'crayfish', 80, 20, 1.4, 'aggressive', 1, true, 'Actively hunts and eats small or bottom-dwelling fish, and will attack passing fish given the chance.', 7.0, 8.0, 8.0, 25.0, 'australian_native', NULL, 'Prolific burrower that eats aquatic plants; not suitable for planted or display tanks with delicate fish.', 'Aquarium Industries yabbies care sheet', 'https://www.aquariumindustries.com.au/wp-content/uploads/2015/03/Yabbies.pdf'),
('Marron', 'Cherax cainii', 'crayfish', 500, 38, 1.5, 'aggressive', 1, true, 'Will nip and eat slow-moving, weak or bottom-resting fish; only pair with robust, active tankmates.', 7.0, 9.0, 20.0, 24.0, 'australian_native', NULL, 'Very large crayfish and a known climber and escape artist; needs a big tank with a secure lid.', 'Aquarium Breeder marron crayfish guide', 'https://aquariumbreeder.com/marron-crayfish-detailed-guide-care-diet-and-breeding/'),
('Rainbow crab', 'Cardisoma armatum', 'crab', 76, 10.2, 1.0, 'aggressive', 1, true, 'Will attempt to eat fish, other crabs and freshly moulted tankmates; keep it on its own.', 7.2, 8.0, 23.9, 29.4, 'west_african_stream', NULL, 'Semi-terrestrial burrower needing land access and brackish-capable water; escapes readily if not secured.', 'The Aquarium Wiki Cardisoma armatum profile', 'https://www.theaquariumwiki.com/wiki/Cardisoma_armatum'),
('Panther crab', 'Parathelphusa pantherina', 'crab', 75, 10, 0.55, 'aggressive', 1, true, 'Will hunt snails, shrimp and sleeping or bottom-resting fish.', 7.5, 8.5, 26.0, 30.0, 'se_asian_stream', NULL, 'Fully aquatic with no land area needed, but a known escape artist needing a tight-fitting lid.', 'Guidarium panther crab care guide', 'https://guidarium.com/fishes/panther-crab'),
('Red mangrove crab', 'Pseudosesarma moeshi', 'crab', 57, 10, 0.3, 'semi-aggressive', 1, false, NULL, 6.8, 7.8, 24.0, 28.0, 'se_asian_stream', NULL, 'Semi-terrestrial and needs land access with high humidity and brackish-capable water; can be territorial toward its own kind.', 'Aqua Imports red mangrove crab profile', 'https://www.aqua-imports.com/product/red-mangrove-crab/'),
('Vampire crab', 'Geosesarma dennerle', 'crab', 19, 3, 0.1, 'semi-aggressive', 1, true, 'Opportunistic predator of shrimp and any fish sharing its enclosure; best kept on its own.', 6.5, 7.5, 22.0, 28.0, 'se_asian_stream', NULL, 'Semi-terrestrial and needs land access with a secure lid, as it is an agile climber.', 'World of Aquariums vampire crab profile', 'https://worldofaquariums.com/fish/vampire-crab')
)
INSERT INTO public.invertebrates (common_name, scientific_name, invert_group, min_tank_litres, adult_size_cm, bioload_factor, temperament, min_group_size, predatory, fish_risk_note, native_ph_min, native_ph_max, native_temp_min_c, native_temp_max_c, biotope_region, algae_role, care_notes, care_source_label, care_source_url, care_reviewed_on, care_confidence)
SELECT n.*, DATE '2026-09-20', 'low'
FROM new_inverts n
WHERE NOT EXISTS (
  SELECT 1 FROM public.invertebrates i
  WHERE lower(i.scientific_name) = lower(n.scientific_name)
);
