-- Second large expansion of the species catalogue.
--
-- Import legality: every species below was matched by scientific name against the
-- DAFF permitted live freshwater ornamental fish list (effective 17 May 2024),
-- checked on 20 Sept 2026, or is an Australian native. daff_listing records the
-- exact list entry matched.
--
-- Care data: adult size and pH/temperature ranges from FishBase, husbandry
-- (minimum tank, group size, temperament) from Seriously Fish. Per-species source
-- URL is stored in care_source_url. care_confidence stays 'low' until a second
-- reviewer checks each row.
--
-- Safe to re-run: a row is only inserted when no species with the same scientific
-- name exists.

WITH new_species (common_name, scientific_name, min_tank_litres, adult_size_cm, bioload_factor, swim_zone, temperament, is_schooling, min_group_size, fin_nipper, predatory, long_finned, active, native_ph_min, native_ph_max, native_temp_min_c, native_temp_max_c, biotope_region, native_habitat_type, conspecific_strategy, conspecific_notes, daff_listing, care_source_label, care_source_url) AS (
  VALUES
('Clown barb', 'Barbodes everetti', 243, 12, 2.3, 'mid', 'semi-aggressive', true, 8, true, false, false, true, 6.0, 7.0, 18, 28, 'se_asian_stream', 'flowing_stream', 'shoal', NULL, 'Barbodes everetti', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/barbodes-everetti'),
('Spanner barb', 'Barbodes lateristriga', 304, 15, 2.8, 'mid', 'semi-aggressive', true, 8, true, false, false, true, 6.0, 8.0, 20, 28, 'se_asian_stream', 'flowing_stream', 'shoal', 'Territorial. Poor match for small or slow tank mates.', 'Barbodes lateristriga', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/barbodes-lateristriga'),
('Filament barb', 'Dawkinsia filamentosa', 243, 12, 2.2, 'mid', 'peaceful', true, 8, false, false, true, true, 6.0, 7.0, 20, 25, 'south_asian_river', 'flowing_stream', 'shoal', 'Males grow long dorsal filaments with age.', 'Dawkinsia filamentosa', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/dawkinsia-filamentosa'),
('Arulius barb', 'Dawkinsia arulius', 243, 10, 1.9, 'mid', 'peaceful', true, 8, false, false, true, true, 6.0, 7.5, 19, 25, 'south_asian_river', 'flowing_stream', 'shoal', NULL, 'Dawkinsia arulius', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/dawkinsia-arulius'),
('Blue danio', 'Danio kerri', 72, 4.5, 0.9, 'top', 'peaceful', true, 8, false, false, false, true, 6.5, 7.5, 18, 26, 'se_asian_stream', 'flowing_stream', 'shoal', NULL, 'Danio kerri', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/brachydanio-kerri'),
('Dwarf spotted danio', 'Danio nigrofasciatus', 54, 4, 0.7, 'mid', 'semi-aggressive', true, 8, true, false, false, true, 6.0, 7.5, 18, 26, 'se_asian_stream', 'flowing_stream', 'shoal', 'Seriously Fish does not rate it as a community fish.', 'Danio nigrofasciatus', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/brachydanio-nigrofasciatus'),
('Bengal danio', 'Devario devario', 243, 8, 1.5, 'top', 'peaceful', true, 8, false, false, false, true, 6.0, 8.0, 15, 26, 'south_asian_river', 'vegetated_margin', 'shoal', 'A jumper. Keep it covered.', 'Devario devario', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/devario-devario'),
('Dwarf rasbora', 'Boraras maculatus', 41, 2.5, 0.4, 'mid', 'peaceful', true, 10, false, false, false, true, 4.0, 6.5, 20, 28, 'se_asian_stream', 'still_blackwater', 'shoal', NULL, 'Boraras maculatus', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/boraras-maculatus'),
('Eyespot rasbora', 'Brevibora dorsiocellata', 41, 3.5, 0.6, 'mid', 'peaceful', true, 8, false, false, false, true, 5.0, 7.5, 20, 25, 'se_asian_stream', 'still_blackwater', 'shoal', NULL, 'Brevibora dorsiocellata', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/brevibora-dorsiocellata'),
('Melon barb', 'Haludaria fasciata', 81, 7, 1.3, 'mid', 'peaceful', true, 8, false, false, false, true, 6.0, 7.5, 22, 26, 'south_asian_river', 'flowing_stream', 'shoal', NULL, 'Haludaria fasciata', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/haludaria-fasciata'),
('Checkered barb', 'Oliotius oligolepis', 68, 4.5, 0.8, 'mid', 'peaceful', true, 8, false, false, false, true, 5.5, 7.5, 18, 25, 'se_asian_stream', 'flowing_stream', 'shoal', NULL, 'Oliotius oligolepis', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/oliotius-oligolepis'),
('Cuming''s barb', 'Pethia cumingii', 54, 4.1, 0.8, 'mid', 'peaceful', true, 8, false, false, false, true, 5.5, 7.0, 20, 27, 'south_asian_river', 'flowing_stream', 'shoal', NULL, 'Pethia cumingii', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/pethia-cumingii'),
('Black ruby barb', 'Pethia nigrofasciata', 72, 6, 1.1, 'mid', 'peaceful', true, 6, false, false, false, true, 6.0, 6.5, 22, 26, 'south_asian_river', 'flowing_stream', 'shoal', 'FishBase suggests groups of five or more.', 'Pethia nigrofasciata', 'FishBase size, range and group guidance', 'https://www.fishbase.se/summary/Pethia-nigrofasciata'),
('Dwarf tiger barb', 'Puntigrus partipentazona', 72, 4, 0.7, 'mid', 'peaceful', true, 8, false, false, false, true, 5.0, 7.0, 20, 26, 'se_asian_stream', 'vegetated_margin', 'shoal', NULL, 'Puntigrus partipentazona', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/puntigrus-partipentazona'),
('Blackline rasbora', 'Rasbora borapetensis', 71, 5, 0.9, 'top', 'peaceful', true, 8, false, false, false, true, 6.0, 7.5, 22, 26, 'se_asian_stream', 'vegetated_margin', 'shoal', NULL, 'Rasbora borapetensis', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/rasbora-borapetensis'),
('Greater scissortail rasbora', 'Rasbora caudimaculata', 319, 15, 2.7, 'mid', 'peaceful', true, 6, false, true, false, true, 6.5, 7.5, 20, 26, 'se_asian_stream', 'flowing_stream', 'shoal', 'Big enough to eat much smaller tank mates.', 'Rasbora caudimaculata', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/rasbora-caudimaculata'),
('Glowlight rasbora', 'Trigonopoma pauciperforatum', 81, 6, 1.0, 'mid', 'peaceful', true, 8, false, false, false, true, 4.0, 7.5, 21, 26, 'se_asian_stream', 'still_blackwater', 'shoal', NULL, 'Trigonopoma pauciperforatum', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/trigonopoma-pauciperforatum'),
('Sawbwa barb', 'Sawbwa resplendens', 54, 3.5, 0.6, 'mid', 'peaceful', true, 8, false, false, false, true, 6.0, 8.0, 18, 22, 'unmapped', 'vegetated_margin', 'shoal', 'Found only in Inle Lake, Myanmar.', 'Sawbwa resplendens (1.5 cm SL minimum)', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/sawbwa-resplendens'),
('Indian glass barb', 'Laubuka laubuca', 108, 6, 1.1, 'top', 'peaceful', true, 8, false, false, false, true, 6.0, 8.0, 18, 24, 'south_asian_river', 'vegetated_margin', 'shoal', NULL, 'Laubuka laubuca', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/laubuka-laubuca'),
('Black kuhli loach', 'Pangio oblonga', 54, 8, 1.3, 'bottom', 'peaceful', false, 8, false, false, false, false, 3.5, 7.0, 21, 26, 'se_asian_stream', 'flowing_stream', 'shoal', 'Sociable. Keep it in a group.', 'Pangio oblonga', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/pangio-oblonga'),
('Splash tetra', 'Copella arnoldi', 95, 4.2, 0.8, 'top', 'peaceful', true, 6, false, false, false, true, 6.0, 8.0, 20, 28, 'amazon_blackwater', 'still_blackwater', 'shoal', 'Spawns on leaves above the water, so keep a tight lid.', 'Copella arnoldi', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/copella-arnoldi'),
('Three-lined pencilfish', 'Nannostomus trifasciatus', 65, 3.6, 0.6, 'mid', 'peaceful', true, 8, false, false, false, false, 5.5, 7.0, 24, 28, 'amazon_blackwater', 'still_blackwater', 'shoal', NULL, 'Nannostomus spp', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/nannostomus-trifasciatus'),
('Purple emperor tetra', 'Inpaichthys kerri', 70, 2.8, 0.5, 'mid', 'peaceful', true, 5, false, false, false, true, 6.0, 8.0, 24, 27, 'amazon_blackwater', 'still_blackwater', 'shoal', 'Stresses and sickens in groups smaller than five.', 'Inpaichthys kerri', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/inpaichthys-kerri'),
('Blue tetra', 'Mimagoniates microlepis', 68, 6.1, 1.0, 'top', 'peaceful', true, 8, false, false, false, true, 6.0, 7.0, 18, 23, 'south_american_river', 'flowing_stream', 'shoal', 'Wants cooler water than most tetras.', 'Mimagoniates microlepis', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/mimagoniates-microlepis'),
('Glass bloodfin tetra', 'Prionobrama filigera', 68, 6.0, 1.0, 'top', 'peaceful', true, 8, false, false, false, true, 6.0, 7.8, 23, 27, 'south_american_river', 'flowing_stream', 'shoal', NULL, 'Prionobrama filigera', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/prionobrama-filigera'),
('False rummy-nose tetra', 'Petitella georgiae', 110, 3.9, 0.8, 'mid', 'peaceful', true, 10, false, false, false, true, 5.5, 7.0, 22, 26, 'south_american_river', 'flowing_stream', 'shoal', 'One of three tetras sold as rummy-nose. Its red is mostly on the head.', 'Petitella georgiae', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/petitella-georgiae'),
('African red-eyed tetra', 'Arnoldichthys spilopterus', 108, 10.0, 1.8, 'mid', 'peaceful', true, 10, false, false, false, true, 6.0, 7.5, 24, 27, 'west_african_stream', 'flowing_stream', 'shoal', 'Known from very few wild sites in Nigeria. Buy captive-bred stock where you can.', 'Arnoldichthys spilopterus', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/arnoldichthys-spilopterus'),
('Long-finned tetra', 'Brycinus longipinnis', 137, 12.5, 2.2, 'mid', 'peaceful', true, 8, false, false, true, true, 6.0, 7.5, 22, 26, 'west_african_stream', 'flowing_stream', 'shoal', 'Sensitive to a dirty tank while settling in.', 'Brycinus longipinnis', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/brycinus-longipinnis'),
('Yellow-tailed Congo tetra', 'Alestopetersius caudalis', 108, 6.2, 1.1, 'mid', 'peaceful', true, 8, false, false, true, true, 6.5, 7.8, 22, 26, 'congo_basin', 'flowing_stream', 'shoal', 'Males carry white-tipped fins that attract nippers.', 'Alestopetersius caudalis', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/alestopetersius-caudalis'),
('Black phantom tetra', 'Hyphessobrycon megalopterus', 72, 3.6, 0.7, 'mid', 'peaceful', true, 8, false, false, true, false, 5.0, 7.0, 20, 28, 'south_american_river', 'flowing_stream', 'shoal', 'Males spar with their enlarged fins. Give them room to break line of sight.', 'Hyphessobrycon spp', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/hyphessobrycon-megalopterus'),
('Flame tetra', 'Hyphessobrycon flammeus', 65, 2.5, 0.5, 'mid', 'peaceful', true, 8, false, false, false, false, 5.5, 7.5, 20, 26, 'unmapped', 'flowing_stream', 'shoal', 'Nearly gone from its native range near Rio de Janeiro. Almost all stock is captive-bred.', 'Hyphessobrycon spp', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/hyphessobrycon-flammeus'),
('Firehead tetra', 'Hemigrammus bleheri', 110, 5.0, 0.9, 'mid', 'peaceful', true, 10, false, false, false, true, 5.5, 7.0, 24, 28, 'amazon_blackwater', 'still_blackwater', 'shoal', 'Also sold as rummy-nose. The red runs further back than in the true rummy-nose.', 'Hemigrammus spp', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/hemigrammus-bleheri'),
('Julii cory', 'Corydoras julii', 81, 5.5, 1.0, 'bottom', 'peaceful', true, 6, false, false, false, false, 5.5, 7.5, 20, 26, 'unmapped', 'flowing_stream', 'shoal', NULL, 'Corydoras spp', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/corydoras-julii'),
('Schwartz''s cory', 'Corydoras schwartzi', 71, 7.0, 1.2, 'bottom', 'peaceful', true, 6, false, false, false, false, 6.0, 7.5, 22, 24, 'amazon_blackwater', 'still_blackwater', 'shoal', 'Needs a clean substrate. Slipping water quality hits it early.', 'Corydoras spp', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/corydoras-schwartzi'),
('Salt and pepper cory', 'Corydoras habrosus', 65, 3.5, 0.6, 'bottom', 'peaceful', true, 8, false, false, false, false, 5.5, 7.5, 20, 26, 'unmapped', 'flowing_stream', 'shoal', 'One of the smallest corydoras.', 'Corydoras spp', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/corydoras-habrosus'),
('Elegant cory', 'Corydoras elegans', 65, 5.5, 0.9, 'bottom', 'peaceful', true, 6, false, false, false, false, 6.0, 7.5, 20, 26, 'amazon_blackwater', 'flowing_stream', 'shoal', NULL, 'Corydoras spp', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/corydoras-elegans'),
('Emerald catfish', 'Brochis splendens', 190, 8.0, 1.5, 'bottom', 'peaceful', true, 6, false, false, false, false, 5.0, 8.0, 20, 28, 'south_american_river', 'flowing_stream', 'shoal', 'Sold as common brochis. Likes slow, densely planted water.', 'Brochis spp', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/corydoras-splendens'),
('Flagtail catfish', 'Dianema urostriatum', 137, 12.5, 2.0, 'bottom', 'peaceful', true, 6, false, false, true, false, 6.0, 8.0, 25, 28, 'south_american_river', 'still_blackwater', 'shoal', 'Wild caught. Newly imported fish are delicate until settled.', 'Dianema urostriatum', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/dianema-urostriatum'),
('Striped glass catfish', 'Kryptopterus macrocephalus', 100, 9.7, 1.6, 'mid', 'peaceful', true, 8, false, false, false, false, 6.5, 7.4, 22, 26, 'se_asian_stream', 'still_blackwater', 'shoal', 'A peat swamp blackwater fish. Wants a mature, dimly lit tank.', 'Kryptopterus macrocephalus', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/kryptopterus-macrocephalus'),
('Agassiz''s dwarf cichlid', 'Apistogramma agassizii', 80, 8, 1.4, 'bottom', 'semi-aggressive', false, 1, false, false, false, false, 5.0, 7.0, 23, 29, 'south_american_river', 'flowing_stream', 'harem', 'Keep one male to two or more females. Males are territorial towards each other.', 'Apistogramma spp', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/apistogramma-agassizii/'),
('Umbrella cichlid', 'Apistogramma borellii', 60, 6, 1.0, 'bottom', 'peaceful', false, 1, false, false, false, false, 6.0, 7.5, 23, 27, 'south_american_river', 'vegetated_margin', 'harem', 'One male to two or more females works best, or a bonded pair.', 'Apistogramma spp', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/apistogramma-borellii/'),
('Threestripe dwarf cichlid', 'Apistogramma trifasciata', 60, 5, 0.9, 'bottom', 'peaceful', false, 1, false, false, false, false, 5.5, 7.0, 23, 29, 'south_american_river', 'vegetated_margin', 'harem', 'One male with several females matches the natural social structure.', 'Apistogramma spp', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/apistogramma-trifasciata/'),
('Panda dwarf cichlid', 'Apistogramma nijsseni', 60, 5.5, 1.0, 'bottom', 'peaceful', false, 1, false, false, false, false, 5.0, 6.0, 25, 29, 'south_american_river', 'flowing_stream', 'harem', 'Best kept as one male to several females.', 'Apistogramma spp', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/apistogramma-nijsseni/'),
('Emperor peacock cichlid', 'Aulonocara nyassae', 250, 15, 2.4, 'mid', 'semi-aggressive', false, 1, false, false, false, true, 7.5, 8.8, 24, 27, 'lake_malawi', 'rocky_rift_lake', 'harem', 'One male to three or more females. Males hold loose territories over sand.', 'Aulonocara nyassae (5 cm SL minimum)', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/aulonocara-nyassae/'),
('Golden dwarf cichlid', 'Nannacara anomala', 80, 7.6, 1.5, 'bottom', 'peaceful', false, 1, false, false, false, false, 6.0, 7.5, 22, 25, 'south_american_river', 'vegetated_margin', 'harem', 'Keep one male with several females. Females guard fry fiercely.', 'Nannacara anomala', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/nannacara-anomala/'),
('Lyretail checkerboard cichlid', 'Dicrossus filamentosus', 71, 10.2, 2.0, 'bottom', 'peaceful', false, 1, false, false, true, false, 4.5, 7.0, 27, 30, 'amazon_blackwater', 'still_blackwater', 'pair', 'Shy. Loses out to pushy tank mates.', 'Dicrossus filamentosus', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/dicrossus-filamentosus/'),
('Dwarf flag cichlid', 'Laetacara curviceps', 60, 5.0, 1.0, 'bottom', 'peaceful', false, 1, false, false, false, false, 4.5, 7.5, 20, 28, 'amazon_blackwater', 'still_blackwater', 'pair', NULL, 'Laetacara curviceps', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/laetacara-curviceps/'),
('Redbreast acara', 'Laetacara dorsigera', 60, 6.0, 1.2, 'bottom', 'peaceful', false, 1, false, false, false, false, 5.0, 7.5, 20, 28, 'south_american_river', 'vegetated_margin', 'pair', 'Territorial around the nest when breeding, peaceful otherwise.', 'Laetacara dorsigera', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/laetacara-dorsigera/'),
('Nicaragua cichlid', 'Hypsophrys nicaraguensis', 243, 25.0, 3.5, 'mid', 'semi-aggressive', false, 1, false, false, false, true, 7.0, 8.0, 23, 28, 'central_american_river', 'flowing_stream', 'pair', 'Territorial, especially when spawning.', 'Hypsophrys nicaraguensis (5 cm SL minimum)', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/hypsophrys-nicaraguensis/'),
('Malawi blue dolphin', 'Cyrtocara moorii', 250, 25.0, 4.0, 'mid', 'peaceful', true, 6, false, false, false, true, 7.5, 8.8, 25, 29, 'lake_malawi', 'open_water', 'shoal', 'Two or three females per male. Males turn territorial when spawning.', 'Cyrtocara moorii', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/cyrtocara-moorii/'),
('Rusty cichlid', 'Iodotropheus sprengerae', 81, 10.0, 1.8, 'bottom', 'semi-aggressive', false, 4, false, false, false, true, 7.5, 8.8, 25, 29, 'lake_malawi', 'rocky_rift_lake', 'harem', 'One of the calmer mbuna, but still an mbuna.', 'Iodotropheus sprengerae', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/iodotropheus-sprengerae/'),
('Lemon cichlid', 'Neolamprologus leleupi', 70, 10.0, 2.0, 'bottom', 'semi-aggressive', false, 1, false, true, false, false, 7.5, 9.0, 23, 27, 'lake_tanganyika', 'rocky_rift_lake', 'pair', 'Hard on its own kind. One pair unless the tank is very large. Eats smaller tank mates.', 'Neolamprologus leleupi (5 cm SL minimum, yellow morph only)', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/neolamprologus-leleupi/'),
('Golden julie', 'Julidochromis ornatus', 68, 8.0, 1.6, 'bottom', 'semi-aggressive', false, 1, false, false, false, false, 7.5, 9.0, 23, 27, 'lake_tanganyika', 'rocky_rift_lake', 'pair', 'Will not tolerate its own kind beyond one pair.', 'Julidochromis spp', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/julidochromis-ornatus/'),
('Brown julie', 'Julidochromis dickfeldi', 68, 8.0, 1.6, 'bottom', 'semi-aggressive', false, 1, false, false, false, false, 8.0, 9.2, 23, 27, 'lake_tanganyika', 'rocky_rift_lake', 'pair', 'Territorial. Best as a single mated pair.', 'Julidochromis spp', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/julidochromis-dickfeldi/'),
('Blunthead cichlid', 'Tropheus moorii', 110, 14.5, 2.9, 'bottom', 'semi-aggressive', true, 8, false, false, false, true, 8.0, 9.5, 23, 27, 'lake_tanganyika', 'rocky_rift_lake', 'colony', 'Squabbles constantly. A big group spreads the aggression. Never feed meaty foods.', 'Tropheus spp (3 cm SL minimum)', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/tropheus-moorii/'),
('Sardine cichlid', 'Cyprichromis leptosoma', 110, 12.5, 2.5, 'mid', 'peaceful', true, 8, false, false, false, true, 7.8, 9.0, 24, 27, 'lake_tanganyika', 'open_water', 'shoal', 'Shoals in open water. Males jump when displaying, so keep it covered.', 'Cyprichromis leptosoma', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/cyprichromis-leptosoma/'),
('Blue-fin paracyprichromis', 'Paracyprichromis nigripinnis', 205, 11.0, 2.2, 'mid', 'peaceful', true, 6, false, false, false, false, 7.5, 9.0, 24, 27, 'lake_tanganyika', 'rocky_rift_lake', 'shoal', 'Loose shoals. Males hold territory under overhangs.', 'Paracyprichromis nigripinnis', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/paracyprichromis-nigripinnis/'),
('Striped goby cichlid', 'Eretmodus cyanostictus', 81, 8.0, 1.6, 'top', 'semi-aggressive', false, 1, false, false, false, true, 8.0, 9.0, 24, 28, 'lake_tanganyika', 'rocky_rift_lake', 'pair', 'Territorial. Lives in the surge zone of rocky shores.', 'Eretmodus cyanostictus', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/eretmodus-cyanostictus/'),
('Striped kribensis', 'Pelvicachromis taeniatus', 71, 8.0, 1.6, 'bottom', 'peaceful', false, 1, false, false, false, false, 5.0, 7.5, 22, 26, 'west_african_stream', 'flowing_stream', 'pair', NULL, 'Pelvicachromis taeniatus', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/pelvicachromis-taeniatus/'),
('Ocellated kribensis', 'Pelvicachromis subocellatus', 71, 8.0, 1.6, 'bottom', 'peaceful', false, 1, false, false, false, false, 5.5, 7.5, 22, 26, 'west_african_stream', 'flowing_stream', 'pair', NULL, 'Pelvicachromis subocellatus', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/pelvicachromis-subocellatus/'),
('Macmaster''s dwarf cichlid', 'Apistogramma macmasteri', 41, 5.5, 1.1, 'bottom', 'peaceful', false, 1, false, false, false, false, 5.5, 7.0, 24, 28, 'south_american_river', 'flowing_stream', 'harem', NULL, 'Apistogramma spp', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/apistogramma-macmasteri/'),
('Hongsloi dwarf cichlid', 'Apistogramma hongsloi', 41, 6.0, 1.2, 'bottom', 'peaceful', false, 1, false, false, false, false, 5.5, 7.0, 23, 29, 'south_american_river', 'still_blackwater', 'harem', NULL, 'Apistogramma spp', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/apistogramma-hongsloi/'),
('Peaceful betta', 'Betta imbellis', 40, 6, 1.2, 'mid', 'semi-aggressive', false, 2, false, false, false, false, 6.0, 8.0, 24, 28, 'se_asian_stream', 'still_blackwater', 'pair', 'Males fight. Keep one, or a pair in a heavily planted tank with a tight lid.', 'Betta spp', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/betta-imbellis/'),
('Licorice gourami', 'Parosphromenus deissneri', 40, 3, 0.6, 'mid', 'peaceful', true, 6, false, false, false, false, 4.0, 6.5, 22, 26, 'se_asian_stream', 'still_blackwater', 'shoal', 'Needs soft acidic blackwater and gentle tank mates, or a tank of its own.', 'Parosphromenus deissneri (2 cm SL minimum)', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/parosphromenus-deissneri/'),
('Croaking gourami', 'Trichopsis vittata', 54, 6.5, 1.3, 'mid', 'peaceful', false, 2, false, false, false, false, 6.0, 8.0, 22, 28, 'se_asian_stream', 'vegetated_margin', 'pair', NULL, 'Trichopsis vittata', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/trichopsis-vittata/'),
('Channoides betta', 'Betta channoides', 40, 5, 1.0, 'mid', 'peaceful', false, 2, false, false, false, false, 4.0, 6.5, 24, 27, 'se_asian_stream', 'still_blackwater', 'pair', 'Soft acidic blackwater suits it best.', 'Betta spp', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/betta-channoides/'),
('Lyretail killifish', 'Aphyosemion australe', 45, 6, 1.2, 'top', 'peaceful', false, 3, false, false, true, false, 5.5, 7.5, 20, 24, 'congo_basin', 'still_blackwater', 'harem', 'Keep as a trio, one male to two or more females.', 'Aphyosemion spp', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/aphyosemion-australe/'),
('Two-stripe killifish', 'Aphyosemion bivittatum', 40, 5, 1.0, 'top', 'peaceful', false, 3, false, false, true, false, 5.5, 6.5, 21, 24, 'congo_basin', 'still_blackwater', 'harem', NULL, 'Aphyosemion spp', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/aphyosemion-bivittatum/'),
('Red chin panchax', 'Epiplatys dageti', 45, 5, 1.0, 'top', 'peaceful', false, 3, false, true, false, true, 6.0, 7.5, 22, 26, 'west_african_stream', 'vegetated_margin', 'harem', 'Will take very small fish, fry and shrimp.', 'Epiplatys spp', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/epiplatys-dageti/'),
('Six-barred panchax', 'Epiplatys sexfasciatus', 60, 8, 1.6, 'top', 'semi-aggressive', false, 2, false, true, false, true, 6.0, 7.5, 23, 26, 'west_african_stream', 'vegetated_margin', 'pair', 'Eats small tank mates and fry.', 'Epiplatys spp', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/epiplatys-sexfasciatus/'),
('Yucatan sailfin molly', 'Poecilia velifera', 200, 15, 3.0, 'top', 'peaceful', false, 4, false, false, true, true, 7.5, 8.5, 22, 28, 'central_american_river', 'vegetated_margin', 'harem', 'One male to several females. Needs algae to graze on.', 'Poecilia velifera', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/poecilia-velifera/'),
('Bulolo rainbowfish', 'Chilatherina bulolo', 250, 10, 2.0, 'mid', 'peaceful', true, 6, false, false, false, true, 6.5, 7.5, 22, 26, 'unmapped', 'flowing_stream', 'shoal', NULL, 'Chilatherina bulolo (4 cm SL minimum)', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/chilatherina-bulolo/'),
('Highland rainbowfish', 'Chilatherina campsi', 200, 9, 1.8, 'mid', 'peaceful', true, 6, false, false, false, true, 6.5, 7.5, 23, 27, 'unmapped', 'flowing_stream', 'shoal', NULL, 'Chilatherina campsi (4 cm SL minimum)', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/chilatherina-campsi/'),
('Lorentz''s rainbowfish', 'Chilatherina lorentzii', 250, 10, 2.0, 'mid', 'peaceful', true, 6, false, false, false, true, 6.5, 7.5, 24, 28, 'unmapped', 'flowing_stream', 'shoal', NULL, 'Chilatherina lorentzii (4 cm SL minimum)', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/chilatherina-lorentzii/'),
('Kabia rainbowfish', 'Glossolepis kabia', 100, 6, 1.2, 'mid', 'peaceful', true, 6, false, false, false, true, 6.5, 7.5, 24, 28, 'unmapped', 'still_blackwater', 'shoal', NULL, 'Glossolepis kabia (4 cm SL minimum)', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/glossolepis-kabia/'),
('Leggett''s rainbowfish', 'Glossolepis leggetti', 150, 8, 1.6, 'mid', 'peaceful', true, 6, false, false, false, true, 6.5, 7.5, 24, 28, 'unmapped', 'still_blackwater', 'shoal', NULL, 'Glossolepis leggetti (4 cm SL minimum)', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/glossolepis-leggetti/'),
('Mamberamo rainbowfish', 'Glossolepis multisquamata', 250, 12, 2.4, 'mid', 'peaceful', true, 6, false, false, false, true, 6.5, 7.5, 24, 28, 'unmapped', 'still_blackwater', 'shoal', NULL, 'Glossolepis multisquamata (4 cm SL minimum)', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/glossolepis-multisquamata/'),
('McCulloch''s rainbowfish', 'Melanotaenia maccullochi', 60, 6, 1.2, 'mid', 'peaceful', true, 6, false, false, false, true, 6.0, 7.5, 23, 27, 'australian_native', 'flowing_stream', 'shoal', 'Some Queensland populations may only be collected under a fisheries permit.', 'NATIVE', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/melanotaenia-maccullochi/'),
('Black-banded rainbowfish', 'Melanotaenia nigrans', 100, 10, 2.0, 'mid', 'peaceful', true, 6, false, false, false, true, 6.0, 8.0, 20, 26, 'australian_native', 'flowing_stream', 'shoal', NULL, 'NATIVE', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/melanotaenia-nigrans/'),
('Western rainbowfish', 'Melanotaenia gracilis', 120, 11, 2.2, 'mid', 'peaceful', true, 6, false, false, false, true, 6.5, 8.0, 18, 28, 'australian_native', 'flowing_stream', 'shoal', 'Collecting in Western Australia needs a fisheries licence.', 'NATIVE', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/melanotaenia-gracilis/'),
('Australian rainbowfish', 'Melanotaenia australis', 120, 10, 2.0, 'mid', 'peaceful', true, 6, false, false, false, true, 6.5, 8.0, 20, 28, 'australian_native', 'flowing_stream', 'shoal', NULL, 'NATIVE', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/melanotaenia-australis/'),
('Cairns rainbowfish', 'Cairnsichthys rhombosomatis', 100, 8, 1.6, 'mid', 'peaceful', true, 6, false, false, false, true, 6.0, 7.5, 20, 26, 'australian_native', 'flowing_stream', 'shoal', 'Wild collection is limited to permitted areas of far north Queensland.', 'NATIVE', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/cairnsichthys-rhombosomatis/'),
('Southern pygmy perch', 'Nannoperca australis', 100, 8, 1.6, 'bottom', 'semi-aggressive', false, 1, false, false, false, false, 6.0, 7.5, 10, 24, 'australian_native', 'vegetated_margin', 'territorial', 'Males hold small territories in dense planting. Some states require a permit to collect.', 'NATIVE', 'Seriously Fish husbandry; FishBase size and range', 'https://www.seriouslyfish.com/species/nannoperca-australis/')
)
INSERT INTO public.species (common_name, scientific_name, min_tank_litres, adult_size_cm, bioload_factor, swim_zone, temperament, is_schooling, min_group_size, fin_nipper, predatory, long_finned, active, native_ph_min, native_ph_max, native_temp_min_c, native_temp_max_c, biotope_region, native_habitat_type, conspecific_strategy, conspecific_notes,
  legal_in_australia, legal_status, legal_note,
  care_source_label, care_source_url, care_reviewed_on, care_confidence)
SELECT n.common_name, n.scientific_name, n.min_tank_litres, n.adult_size_cm, n.bioload_factor, n.swim_zone, n.temperament, n.is_schooling, n.min_group_size, n.fin_nipper, n.predatory, n.long_finned, n.active, n.native_ph_min, n.native_ph_max, n.native_temp_min_c, n.native_temp_max_c, n.biotope_region, n.native_habitat_type, n.conspecific_strategy, n.conspecific_notes,
  true,
  CASE WHEN n.daff_listing = 'NATIVE' THEN 'native' ELSE 'permitted' END,
  CASE WHEN n.daff_listing = 'NATIVE'
    THEN 'Australian native. Collection and keeping rules vary by state and territory.'
    ELSE 'Listed on the DAFF permitted freshwater ornamental fish list as ' || n.daff_listing || '.' END,
  n.care_source_label, n.care_source_url, DATE '2026-09-20', 'low'
FROM new_species n
WHERE NOT EXISTS (
  SELECT 1 FROM public.species s
  WHERE lower(s.scientific_name) = lower(n.scientific_name)
);
